services:
  app:
    build: ./app
    container_name: otel-app
    ports:
      - "9000:9000"

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/dashboard.yml:/etc/grafana/provisioning/dashboards/dashboard.yml:ro
      - ./grafana/dice-dashboard.json:/etc/grafana/provisioning/dashboards/dice-dashboard.json:ro
      - ./grafana/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml:ro
